version: '3'
services:
  consumer:
    build: .
    env_file:
      - env_file
    volumes:
      - .:/opt/services/consumer/src
    networks:
      - web_nw
  nginx:
    image: nginx:1.21.6
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - consumer
networks:
  web_nw:
    driver: bridge
